@startuml
class Espectador{
    String nom 
    int edat 
    double diners 
-Espectador(String nom, int edat, double diners)
-Espectador(int edat, double diners)
-Espectador(double diners)  
-String getNom( )  
-String setNom( )
-int getEdat( )
-int getEdat( )
-boolean getMajorEdat( )
-boolean setMajorEdat( )
-boolean teDiners(double preuEntrada)
-double pagarntrada(double preuEntrada)
-void waled( )
-double setWalet( )
-double setRecarrega( )
-String toStrring( )
-void seients( )
}


@enduml
